### ISSUE TITLE
Dedicated UI

### ISSUE THREAD

**Issue by Hyperion-21** [Hyperion-21/GalaxyTweaker#1]
Ideally, upon clicking the "Create New Campaign" button, a custom window.

- [x] Make a window appear
- [x] Make that window appear when clicking Create New Campaign
- [x] Be able to type in string
- [x] Load GalaxyDefinition from string
- [x] Make the menu a drop-down that automatically finds GalaxyDefinitions

**Comment by JohnsterSpaceProgramOfficial** [comment]
Hello. If you want, I think I could help you out with implementing this.

Edit: Here's a UI concept I made that would function similar to what you would want it to do. Pressing reload galaxy definitions would update the list of found galaxy definitions in the folder where they are stored. And to select one of them, you would just click on the button with the name of that galaxy definition.

![Screenshot 2023-03-21 105537](https://user-images.githubusercontent.com/61912428/226647530-db2e4972-4693-4547-ab5a-5834d61516f7.png)

https://user-images.githubusercontent.com/61912428/226652432-2952bfd7-7382-4d9e-add3-d65dcc86e23a.mp4
