### ISSUE TITLE
Cannot move moons to other planets

### ISSUE THREAD

**Issue by Jan-Arbus** [Hyperion-21/GalaxyTweaker#11]
I tried to move Gilly to Kerbin, but the game went wrong and couldn't create save
Here is the config file and log
[log.log](https://github.com/Hyperion-21/GalaxyTweaker/files/11066874/log.log)
[Config.zip](https://github.com/Hyperion-21/GalaxyTweaker/files/11066876/Config.zip)

**Comment by Hyperion-21** [comment]
Sorry for taking so long to get to this.

The issue is that Gilly is calling Kerbin before Kerbin exists. Gilly must be defined *after* Kerbin. I'd recommend copy-pasting the Gilly section to be under Kerbin.
